/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R401RouteImport } from './routes/401'
import { Route as R403RouteImport } from './routes/403'
import { Route as R404RouteImport } from './routes/404'
import { Route as R500RouteImport } from './routes/500'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthenticatedAccessControlRouteImport } from './routes/_authenticated/access-control'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFarmersRouteImport } from './routes/_authenticated/farmers'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedTransferStockRouteImport } from './routes/_authenticated/transfer-stock'
import { Route as AuthenticatedAccessControlPermissionsRouteImport } from './routes/_authenticated/access-control.permissions'
import { Route as AuthenticatedAccessControlSessionsRouteImport } from './routes/_authenticated/access-control.sessions'
import { Route as AuthenticatedAccessControlUsersRouteImport } from './routes/_authenticated/access-control.users'
import { Route as AuthenticatedFarmersIdRouteImport } from './routes/_authenticated/farmers.$id'
import { Route as AuthenticatedFarmersAnalyticsRouteImport } from './routes/_authenticated/farmers.analytics'
import { Route as AuthenticatedFarmersContractRouteImport } from './routes/_authenticated/farmers.contract'
import { Route as AuthenticatedFarmersOverviewRouteImport } from './routes/_authenticated/farmers.overview'
import { Route as AuthenticatedFarmersReportRouteImport } from './routes/_authenticated/farmers.report'
import { Route as AuthenticatedMasterFacilitiesRouteImport } from './routes/_authenticated/master.facilities'
import { Route as AuthenticatedMasterGenerationsRouteImport } from './routes/_authenticated/master.generations'
import { Route as AuthenticatedMasterSeedSizesRouteImport } from './routes/_authenticated/master.seed-sizes'
import { Route as AuthenticatedMasterStationsRouteImport } from './routes/_authenticated/master.stations'
import { Route as AuthenticatedMasterTuberSizesRouteImport } from './routes/_authenticated/master.tuber-sizes'
import { Route as AuthenticatedMasterVarietiesRouteImport } from './routes/_authenticated/master.varieties'
import { Route as AuthenticatedSeedDispatchesAnalyticsRouteImport } from './routes/_authenticated/seed-dispatches.analytics'
import { Route as AuthenticatedSeedDispatchesOverviewRouteImport } from './routes/_authenticated/seed-dispatches.overview'
import { Route as AuthenticatedSeedDispatchesSettingsRouteImport } from './routes/_authenticated/seed-dispatches.settings'
import { Route as AuthenticatedSeedRequisitionAnalyticsRouteImport } from './routes/_authenticated/seed-requisition.analytics'
import { Route as AuthenticatedSeedRequisitionOverviewRouteImport } from './routes/_authenticated/seed-requisition.overview'
import { Route as AuthenticatedSeedRequisitionSettingsRouteImport } from './routes/_authenticated/seed-requisition.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessControlRoute =
  AuthenticatedAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFarmersRoute = AuthenticatedFarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransferStockRoute =
  AuthenticatedTransferStockRouteImport.update({
    id: '/transfer-stock',
    path: '/transfer-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessControlPermissionsRoute =
  AuthenticatedAccessControlPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAccessControlRoute,
  } as any)
const AuthenticatedAccessControlSessionsRoute =
  AuthenticatedAccessControlSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAccessControlRoute,
  } as any)
const AuthenticatedAccessControlUsersRoute =
  AuthenticatedAccessControlUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAccessControlRoute,
  } as any)
const AuthenticatedFarmersIdRoute = AuthenticatedFarmersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFarmersRoute,
} as any)
const AuthenticatedFarmersAnalyticsRoute =
  AuthenticatedFarmersAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)
const AuthenticatedFarmersContractRoute =
  AuthenticatedFarmersContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)
const AuthenticatedFarmersOverviewRoute =
  AuthenticatedFarmersOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)
const AuthenticatedFarmersReportRoute =
  AuthenticatedFarmersReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedFarmersRoute,
  } as any)
const AuthenticatedMasterFacilitiesRoute =
  AuthenticatedMasterFacilitiesRouteImport.update({
    id: '/facilities',
    path: '/facilities',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterGenerationsRoute =
  AuthenticatedMasterGenerationsRouteImport.update({
    id: '/generations',
    path: '/generations',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterSeedSizesRoute =
  AuthenticatedMasterSeedSizesRouteImport.update({
    id: '/seed-sizes',
    path: '/seed-sizes',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterStationsRoute =
  AuthenticatedMasterStationsRouteImport.update({
    id: '/stations',
    path: '/stations',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterTuberSizesRoute =
  AuthenticatedMasterTuberSizesRouteImport.update({
    id: '/tuber-sizes',
    path: '/tuber-sizes',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterVarietiesRoute =
  AuthenticatedMasterVarietiesRouteImport.update({
    id: '/varieties',
    path: '/varieties',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedSeedDispatchesAnalyticsRoute =
  AuthenticatedSeedDispatchesAnalyticsRouteImport.update({
    id: '/seed-dispatches/analytics',
    path: '/seed-dispatches/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeedDispatchesOverviewRoute =
  AuthenticatedSeedDispatchesOverviewRouteImport.update({
    id: '/seed-dispatches/overview',
    path: '/seed-dispatches/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeedDispatchesSettingsRoute =
  AuthenticatedSeedDispatchesSettingsRouteImport.update({
    id: '/seed-dispatches/settings',
    path: '/seed-dispatches/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeedRequisitionAnalyticsRoute =
  AuthenticatedSeedRequisitionAnalyticsRouteImport.update({
    id: '/seed-requisition/analytics',
    path: '/seed-requisition/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeedRequisitionOverviewRoute =
  AuthenticatedSeedRequisitionOverviewRouteImport.update({
    id: '/seed-requisition/overview',
    path: '/seed-requisition/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeedRequisitionSettingsRoute =
  AuthenticatedSeedRequisitionSettingsRouteImport.update({
    id: '/seed-requisition/settings',
    path: '/seed-requisition/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/coming-soon': typeof ComingSoonRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/access-control': typeof AuthenticatedAccessControlRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/transfer-stock': typeof AuthenticatedTransferStockRoute
  '/access-control/permissions': typeof AuthenticatedAccessControlPermissionsRoute
  '/access-control/sessions': typeof AuthenticatedAccessControlSessionsRoute
  '/access-control/users': typeof AuthenticatedAccessControlUsersRoute
  '/farmers/$id': typeof AuthenticatedFarmersIdRoute
  '/farmers/analytics': typeof AuthenticatedFarmersAnalyticsRoute
  '/farmers/contract': typeof AuthenticatedFarmersContractRoute
  '/farmers/overview': typeof AuthenticatedFarmersOverviewRoute
  '/farmers/report': typeof AuthenticatedFarmersReportRoute
  '/master/facilities': typeof AuthenticatedMasterFacilitiesRoute
  '/master/generations': typeof AuthenticatedMasterGenerationsRoute
  '/master/seed-sizes': typeof AuthenticatedMasterSeedSizesRoute
  '/master/stations': typeof AuthenticatedMasterStationsRoute
  '/master/tuber-sizes': typeof AuthenticatedMasterTuberSizesRoute
  '/master/varieties': typeof AuthenticatedMasterVarietiesRoute
  '/seed-dispatches/analytics': typeof AuthenticatedSeedDispatchesAnalyticsRoute
  '/seed-dispatches/overview': typeof AuthenticatedSeedDispatchesOverviewRoute
  '/seed-dispatches/settings': typeof AuthenticatedSeedDispatchesSettingsRoute
  '/seed-requisition/analytics': typeof AuthenticatedSeedRequisitionAnalyticsRoute
  '/seed-requisition/overview': typeof AuthenticatedSeedRequisitionOverviewRoute
  '/seed-requisition/settings': typeof AuthenticatedSeedRequisitionSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/coming-soon': typeof ComingSoonRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/access-control': typeof AuthenticatedAccessControlRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/transfer-stock': typeof AuthenticatedTransferStockRoute
  '/access-control/permissions': typeof AuthenticatedAccessControlPermissionsRoute
  '/access-control/sessions': typeof AuthenticatedAccessControlSessionsRoute
  '/access-control/users': typeof AuthenticatedAccessControlUsersRoute
  '/farmers/$id': typeof AuthenticatedFarmersIdRoute
  '/farmers/analytics': typeof AuthenticatedFarmersAnalyticsRoute
  '/farmers/contract': typeof AuthenticatedFarmersContractRoute
  '/farmers/overview': typeof AuthenticatedFarmersOverviewRoute
  '/farmers/report': typeof AuthenticatedFarmersReportRoute
  '/master/facilities': typeof AuthenticatedMasterFacilitiesRoute
  '/master/generations': typeof AuthenticatedMasterGenerationsRoute
  '/master/seed-sizes': typeof AuthenticatedMasterSeedSizesRoute
  '/master/stations': typeof AuthenticatedMasterStationsRoute
  '/master/tuber-sizes': typeof AuthenticatedMasterTuberSizesRoute
  '/master/varieties': typeof AuthenticatedMasterVarietiesRoute
  '/seed-dispatches/analytics': typeof AuthenticatedSeedDispatchesAnalyticsRoute
  '/seed-dispatches/overview': typeof AuthenticatedSeedDispatchesOverviewRoute
  '/seed-dispatches/settings': typeof AuthenticatedSeedDispatchesSettingsRoute
  '/seed-requisition/analytics': typeof AuthenticatedSeedRequisitionAnalyticsRoute
  '/seed-requisition/overview': typeof AuthenticatedSeedRequisitionOverviewRoute
  '/seed-requisition/settings': typeof AuthenticatedSeedRequisitionSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/_authenticated/access-control': typeof AuthenticatedAccessControlRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/farmers': typeof AuthenticatedFarmersRouteWithChildren
  '/_authenticated/master': typeof AuthenticatedMasterRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/transfer-stock': typeof AuthenticatedTransferStockRoute
  '/_authenticated/access-control/permissions': typeof AuthenticatedAccessControlPermissionsRoute
  '/_authenticated/access-control/sessions': typeof AuthenticatedAccessControlSessionsRoute
  '/_authenticated/access-control/users': typeof AuthenticatedAccessControlUsersRoute
  '/_authenticated/farmers/$id': typeof AuthenticatedFarmersIdRoute
  '/_authenticated/farmers/analytics': typeof AuthenticatedFarmersAnalyticsRoute
  '/_authenticated/farmers/contract': typeof AuthenticatedFarmersContractRoute
  '/_authenticated/farmers/overview': typeof AuthenticatedFarmersOverviewRoute
  '/_authenticated/farmers/report': typeof AuthenticatedFarmersReportRoute
  '/_authenticated/master/facilities': typeof AuthenticatedMasterFacilitiesRoute
  '/_authenticated/master/generations': typeof AuthenticatedMasterGenerationsRoute
  '/_authenticated/master/seed-sizes': typeof AuthenticatedMasterSeedSizesRoute
  '/_authenticated/master/stations': typeof AuthenticatedMasterStationsRoute
  '/_authenticated/master/tuber-sizes': typeof AuthenticatedMasterTuberSizesRoute
  '/_authenticated/master/varieties': typeof AuthenticatedMasterVarietiesRoute
  '/_authenticated/seed-dispatches/analytics': typeof AuthenticatedSeedDispatchesAnalyticsRoute
  '/_authenticated/seed-dispatches/overview': typeof AuthenticatedSeedDispatchesOverviewRoute
  '/_authenticated/seed-dispatches/settings': typeof AuthenticatedSeedDispatchesSettingsRoute
  '/_authenticated/seed-requisition/analytics': typeof AuthenticatedSeedRequisitionAnalyticsRoute
  '/_authenticated/seed-requisition/overview': typeof AuthenticatedSeedRequisitionOverviewRoute
  '/_authenticated/seed-requisition/settings': typeof AuthenticatedSeedRequisitionSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/coming-soon'
    | '/error'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/access-control'
    | '/dashboard'
    | '/farmers'
    | '/master'
    | '/messages'
    | '/notifications'
    | '/transfer-stock'
    | '/access-control/permissions'
    | '/access-control/sessions'
    | '/access-control/users'
    | '/farmers/$id'
    | '/farmers/analytics'
    | '/farmers/contract'
    | '/farmers/overview'
    | '/farmers/report'
    | '/master/facilities'
    | '/master/generations'
    | '/master/seed-sizes'
    | '/master/stations'
    | '/master/tuber-sizes'
    | '/master/varieties'
    | '/seed-dispatches/analytics'
    | '/seed-dispatches/overview'
    | '/seed-dispatches/settings'
    | '/seed-requisition/analytics'
    | '/seed-requisition/overview'
    | '/seed-requisition/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/coming-soon'
    | '/error'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/access-control'
    | '/dashboard'
    | '/farmers'
    | '/master'
    | '/messages'
    | '/notifications'
    | '/transfer-stock'
    | '/access-control/permissions'
    | '/access-control/sessions'
    | '/access-control/users'
    | '/farmers/$id'
    | '/farmers/analytics'
    | '/farmers/contract'
    | '/farmers/overview'
    | '/farmers/report'
    | '/master/facilities'
    | '/master/generations'
    | '/master/seed-sizes'
    | '/master/stations'
    | '/master/tuber-sizes'
    | '/master/varieties'
    | '/seed-dispatches/analytics'
    | '/seed-dispatches/overview'
    | '/seed-dispatches/settings'
    | '/seed-requisition/analytics'
    | '/seed-requisition/overview'
    | '/seed-requisition/settings'
  id:
    | '__root__'
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/_authenticated'
    | '/coming-soon'
    | '/error'
    | '/login'
    | '/maintenance'
    | '/offline'
    | '/_authenticated/access-control'
    | '/_authenticated/dashboard'
    | '/_authenticated/farmers'
    | '/_authenticated/master'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/transfer-stock'
    | '/_authenticated/access-control/permissions'
    | '/_authenticated/access-control/sessions'
    | '/_authenticated/access-control/users'
    | '/_authenticated/farmers/$id'
    | '/_authenticated/farmers/analytics'
    | '/_authenticated/farmers/contract'
    | '/_authenticated/farmers/overview'
    | '/_authenticated/farmers/report'
    | '/_authenticated/master/facilities'
    | '/_authenticated/master/generations'
    | '/_authenticated/master/seed-sizes'
    | '/_authenticated/master/stations'
    | '/_authenticated/master/tuber-sizes'
    | '/_authenticated/master/varieties'
    | '/_authenticated/seed-dispatches/analytics'
    | '/_authenticated/seed-dispatches/overview'
    | '/_authenticated/seed-dispatches/settings'
    | '/_authenticated/seed-requisition/analytics'
    | '/_authenticated/seed-requisition/overview'
    | '/_authenticated/seed-requisition/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-control': {
      id: '/_authenticated/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AuthenticatedAccessControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/farmers': {
      id: '/_authenticated/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof AuthenticatedFarmersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer-stock': {
      id: '/_authenticated/transfer-stock'
      path: '/transfer-stock'
      fullPath: '/transfer-stock'
      preLoaderRoute: typeof AuthenticatedTransferStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-control/permissions': {
      id: '/_authenticated/access-control/permissions'
      path: '/permissions'
      fullPath: '/access-control/permissions'
      preLoaderRoute: typeof AuthenticatedAccessControlPermissionsRouteImport
      parentRoute: typeof AuthenticatedAccessControlRoute
    }
    '/_authenticated/access-control/sessions': {
      id: '/_authenticated/access-control/sessions'
      path: '/sessions'
      fullPath: '/access-control/sessions'
      preLoaderRoute: typeof AuthenticatedAccessControlSessionsRouteImport
      parentRoute: typeof AuthenticatedAccessControlRoute
    }
    '/_authenticated/access-control/users': {
      id: '/_authenticated/access-control/users'
      path: '/users'
      fullPath: '/access-control/users'
      preLoaderRoute: typeof AuthenticatedAccessControlUsersRouteImport
      parentRoute: typeof AuthenticatedAccessControlRoute
    }
    '/_authenticated/farmers/$id': {
      id: '/_authenticated/farmers/$id'
      path: '/$id'
      fullPath: '/farmers/$id'
      preLoaderRoute: typeof AuthenticatedFarmersIdRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/analytics': {
      id: '/_authenticated/farmers/analytics'
      path: '/analytics'
      fullPath: '/farmers/analytics'
      preLoaderRoute: typeof AuthenticatedFarmersAnalyticsRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/contract': {
      id: '/_authenticated/farmers/contract'
      path: '/contract'
      fullPath: '/farmers/contract'
      preLoaderRoute: typeof AuthenticatedFarmersContractRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/overview': {
      id: '/_authenticated/farmers/overview'
      path: '/overview'
      fullPath: '/farmers/overview'
      preLoaderRoute: typeof AuthenticatedFarmersOverviewRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/farmers/report': {
      id: '/_authenticated/farmers/report'
      path: '/report'
      fullPath: '/farmers/report'
      preLoaderRoute: typeof AuthenticatedFarmersReportRouteImport
      parentRoute: typeof AuthenticatedFarmersRoute
    }
    '/_authenticated/master/facilities': {
      id: '/_authenticated/master/facilities'
      path: '/facilities'
      fullPath: '/master/facilities'
      preLoaderRoute: typeof AuthenticatedMasterFacilitiesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/generations': {
      id: '/_authenticated/master/generations'
      path: '/generations'
      fullPath: '/master/generations'
      preLoaderRoute: typeof AuthenticatedMasterGenerationsRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/seed-sizes': {
      id: '/_authenticated/master/seed-sizes'
      path: '/seed-sizes'
      fullPath: '/master/seed-sizes'
      preLoaderRoute: typeof AuthenticatedMasterSeedSizesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/stations': {
      id: '/_authenticated/master/stations'
      path: '/stations'
      fullPath: '/master/stations'
      preLoaderRoute: typeof AuthenticatedMasterStationsRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/tuber-sizes': {
      id: '/_authenticated/master/tuber-sizes'
      path: '/tuber-sizes'
      fullPath: '/master/tuber-sizes'
      preLoaderRoute: typeof AuthenticatedMasterTuberSizesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/varieties': {
      id: '/_authenticated/master/varieties'
      path: '/varieties'
      fullPath: '/master/varieties'
      preLoaderRoute: typeof AuthenticatedMasterVarietiesRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/seed-dispatches/analytics': {
      id: '/_authenticated/seed-dispatches/analytics'
      path: '/seed-dispatches/analytics'
      fullPath: '/seed-dispatches/analytics'
      preLoaderRoute: typeof AuthenticatedSeedDispatchesAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seed-dispatches/overview': {
      id: '/_authenticated/seed-dispatches/overview'
      path: '/seed-dispatches/overview'
      fullPath: '/seed-dispatches/overview'
      preLoaderRoute: typeof AuthenticatedSeedDispatchesOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seed-dispatches/settings': {
      id: '/_authenticated/seed-dispatches/settings'
      path: '/seed-dispatches/settings'
      fullPath: '/seed-dispatches/settings'
      preLoaderRoute: typeof AuthenticatedSeedDispatchesSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seed-requisition/analytics': {
      id: '/_authenticated/seed-requisition/analytics'
      path: '/seed-requisition/analytics'
      fullPath: '/seed-requisition/analytics'
      preLoaderRoute: typeof AuthenticatedSeedRequisitionAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seed-requisition/overview': {
      id: '/_authenticated/seed-requisition/overview'
      path: '/seed-requisition/overview'
      fullPath: '/seed-requisition/overview'
      preLoaderRoute: typeof AuthenticatedSeedRequisitionOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seed-requisition/settings': {
      id: '/_authenticated/seed-requisition/settings'
      path: '/seed-requisition/settings'
      fullPath: '/seed-requisition/settings'
      preLoaderRoute: typeof AuthenticatedSeedRequisitionSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAccessControlRouteChildren {
  AuthenticatedAccessControlPermissionsRoute: typeof AuthenticatedAccessControlPermissionsRoute
  AuthenticatedAccessControlSessionsRoute: typeof AuthenticatedAccessControlSessionsRoute
  AuthenticatedAccessControlUsersRoute: typeof AuthenticatedAccessControlUsersRoute
}

const AuthenticatedAccessControlRouteChildren: AuthenticatedAccessControlRouteChildren =
  {
    AuthenticatedAccessControlPermissionsRoute:
      AuthenticatedAccessControlPermissionsRoute,
    AuthenticatedAccessControlSessionsRoute:
      AuthenticatedAccessControlSessionsRoute,
    AuthenticatedAccessControlUsersRoute: AuthenticatedAccessControlUsersRoute,
  }

const AuthenticatedAccessControlRouteWithChildren =
  AuthenticatedAccessControlRoute._addFileChildren(
    AuthenticatedAccessControlRouteChildren,
  )

interface AuthenticatedFarmersRouteChildren {
  AuthenticatedFarmersIdRoute: typeof AuthenticatedFarmersIdRoute
  AuthenticatedFarmersAnalyticsRoute: typeof AuthenticatedFarmersAnalyticsRoute
  AuthenticatedFarmersContractRoute: typeof AuthenticatedFarmersContractRoute
  AuthenticatedFarmersOverviewRoute: typeof AuthenticatedFarmersOverviewRoute
  AuthenticatedFarmersReportRoute: typeof AuthenticatedFarmersReportRoute
}

const AuthenticatedFarmersRouteChildren: AuthenticatedFarmersRouteChildren = {
  AuthenticatedFarmersIdRoute: AuthenticatedFarmersIdRoute,
  AuthenticatedFarmersAnalyticsRoute: AuthenticatedFarmersAnalyticsRoute,
  AuthenticatedFarmersContractRoute: AuthenticatedFarmersContractRoute,
  AuthenticatedFarmersOverviewRoute: AuthenticatedFarmersOverviewRoute,
  AuthenticatedFarmersReportRoute: AuthenticatedFarmersReportRoute,
}

const AuthenticatedFarmersRouteWithChildren =
  AuthenticatedFarmersRoute._addFileChildren(AuthenticatedFarmersRouteChildren)

interface AuthenticatedMasterRouteChildren {
  AuthenticatedMasterFacilitiesRoute: typeof AuthenticatedMasterFacilitiesRoute
  AuthenticatedMasterGenerationsRoute: typeof AuthenticatedMasterGenerationsRoute
  AuthenticatedMasterSeedSizesRoute: typeof AuthenticatedMasterSeedSizesRoute
  AuthenticatedMasterStationsRoute: typeof AuthenticatedMasterStationsRoute
  AuthenticatedMasterTuberSizesRoute: typeof AuthenticatedMasterTuberSizesRoute
  AuthenticatedMasterVarietiesRoute: typeof AuthenticatedMasterVarietiesRoute
}

const AuthenticatedMasterRouteChildren: AuthenticatedMasterRouteChildren = {
  AuthenticatedMasterFacilitiesRoute: AuthenticatedMasterFacilitiesRoute,
  AuthenticatedMasterGenerationsRoute: AuthenticatedMasterGenerationsRoute,
  AuthenticatedMasterSeedSizesRoute: AuthenticatedMasterSeedSizesRoute,
  AuthenticatedMasterStationsRoute: AuthenticatedMasterStationsRoute,
  AuthenticatedMasterTuberSizesRoute: AuthenticatedMasterTuberSizesRoute,
  AuthenticatedMasterVarietiesRoute: AuthenticatedMasterVarietiesRoute,
}

const AuthenticatedMasterRouteWithChildren =
  AuthenticatedMasterRoute._addFileChildren(AuthenticatedMasterRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccessControlRoute: typeof AuthenticatedAccessControlRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFarmersRoute: typeof AuthenticatedFarmersRouteWithChildren
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedTransferStockRoute: typeof AuthenticatedTransferStockRoute
  AuthenticatedSeedDispatchesAnalyticsRoute: typeof AuthenticatedSeedDispatchesAnalyticsRoute
  AuthenticatedSeedDispatchesOverviewRoute: typeof AuthenticatedSeedDispatchesOverviewRoute
  AuthenticatedSeedDispatchesSettingsRoute: typeof AuthenticatedSeedDispatchesSettingsRoute
  AuthenticatedSeedRequisitionAnalyticsRoute: typeof AuthenticatedSeedRequisitionAnalyticsRoute
  AuthenticatedSeedRequisitionOverviewRoute: typeof AuthenticatedSeedRequisitionOverviewRoute
  AuthenticatedSeedRequisitionSettingsRoute: typeof AuthenticatedSeedRequisitionSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessControlRoute: AuthenticatedAccessControlRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFarmersRoute: AuthenticatedFarmersRouteWithChildren,
  AuthenticatedMasterRoute: AuthenticatedMasterRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedTransferStockRoute: AuthenticatedTransferStockRoute,
  AuthenticatedSeedDispatchesAnalyticsRoute:
    AuthenticatedSeedDispatchesAnalyticsRoute,
  AuthenticatedSeedDispatchesOverviewRoute:
    AuthenticatedSeedDispatchesOverviewRoute,
  AuthenticatedSeedDispatchesSettingsRoute:
    AuthenticatedSeedDispatchesSettingsRoute,
  AuthenticatedSeedRequisitionAnalyticsRoute:
    AuthenticatedSeedRequisitionAnalyticsRoute,
  AuthenticatedSeedRequisitionOverviewRoute:
    AuthenticatedSeedRequisitionOverviewRoute,
  AuthenticatedSeedRequisitionSettingsRoute:
    AuthenticatedSeedRequisitionSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
